### ISSUE TITLE
process.binding deprecation

### ISSUE THREAD

**Issue by RafaelGSS** [clinicjs/node-clinic-bubbleprof#383]
This module uses `process.binding('async_wrap').Providers` to get system info, however, the `process.binding` was deprecated in node v16+.

As far I know, there is no public way anymore to get this kind of data. Looks like a need to create a public API under `async_hooks` (?) for that.

This issue aims to keep tracking of this work.

**Comment by mcollina** [comment]
I supected some of this. What data is actually needed? Could you open a PR against Node Core to expose that?

**Comment by RafaelGSS** [comment]
https://github.com/nodejs/node/issues/40730

**Comment by RafaelGSS** [comment]
The node pr was merged, waiting for the release version.
