### ISSUE TITLE
There was a decoding error with chunk (base64)

### ISSUE THREAD

**Issue by ff6347** [clinicjs/node-clinic-bubbleprof#395]
While using bubbleprof on a Typescript project I get the error on the title with the request to open an issue here.

I attached the chunk. Let me know if you also need the generated files
[clinic-bubbleprof-base64-chunk.txt](https://github.com/clinicjs/node-clinic-bubbleprof/files/8283880/clinic-bubbleprof-base64-chunk.txt)

**Comment by RafaelGSS** [comment]
Can you create a reproductible example?

**Comment by ff6347** [comment]
Hi. Sorry for the delay. Creating a reproducible example is hard, since my application depends on a set of docker containers run from a docker-compose.yml and is written in typescript.

**Comment by mattbishop** [comment]
I ran into this today, it said to report the following chunk:

```
There was a decoding error with chunk (base64):
 ... see attached file
Please open an issue on https://github.com/clinicjs/node-clinic-bubbleprof with the above output.
```
[base-64-chunk.txt](https://github.com/clinicjs/node-clinic-bubbleprof/files/10201417/base-64-chunk.txt)

**Comment by ff6347** [comment]
Hi @stearm yes I know. My project was to large to slim it down at that moment and time was an issue. Sorry for the noise. I'll do better next time.

**Comment by stearm** [comment]
> Hi @stearm yes I know. My project was to large to slim it down at that moment and time was an issue. Sorry for the noise. I'll do better next time.

No worries, we're here to help each other 😄 !

**Comment by vamshi9666** [comment]
i am facing same error. Error is encoded and unreadable

**Comment by RafaelGSS** [comment]
> i am facing same error. Error is encoded and unreadable

Please open a new issue with a reproducible code.
