### ISSUE TITLE
Inclusion of pino-pretty while running bubbleprof results in userland data not being shown

### ISSUE THREAD

**Issue by markrzen** [clinicjs/node-clinic-bubbleprof#398]
Repro. repo
https://github.com/markrzen/bubbleprof-pino-pretty-issue

I have pino pretty being included on NODE_ENV=development, and not in =production.

I suspect this is an issue similar to the call out about Jest, but it felt odd as this code works fine for Doctor.

---

The inclusion of pino-pretty seems to prevent user-land data from showing up.
`NODE_ENV=development clinic bubble -- node index.js`

Without pino-pretty, it all works as expected
`NODE_ENV=production clinic bubble -- node index.js`

**Comment by RafaelGSS** [comment]
Hi @markrzen 

I've run it locally and it's working fine for me. Can you:

- Install the latest clinic version
- Take a few screenshots
- Provide your OS details?
